# -*- coding: utf-8 -*-
#人工判定的分类 + 中文一句话说明
# key = owner/repo

CATS = {
    "ai-agent": ("AI Agent 与智能体应用", "🤖"),
    "ai-infra": ("大模型训练、推理与基础设施", "🧠"),
    "finance": ("金融量化与投资研究", "📈"),
    "reading": ("电子书与阅读器", "📖"),
    "rss-news": ("RSS、资讯与舆情监控", "📰"),
    "crawl-browser": ("爬虫与浏览器自动化", "🕷️"),
    "tools": ("实用工具与效率软件", "🛠️"),
    "mobile": ("Android / 移动端开发", "📱"),
    "media": ("影音媒体与家庭娱乐", "🎬"),
    "system": ("硬件、系统与嵌入式", "⚙️"),
    "frontend": ("前端与网页开发", "🌐"),
    "learning": ("学习资料与教程", "📚"),
    "games": ("游戏与模拟器", "🎮"),
    "security": ("隐私、安全与逆向", "🔒"),
    "life": ("生活、健康与个人成长", "🌱"),
}

# repo -> (category, 中文说明)
NOTES = {
    # ---------- AI Agent 与智能体应用 ----------
    "n8n-io/n8n": ("ai-agent", "可视化搭建 AI 工作流的自托管平台，400+ 集成，可写自定义代码节点"),
    "minhalvp/android-mcp-server": ("ai-agent", "通过 adb 控制安卓设备的 MCP Server，让 Agent 直接操作手机"),
    "firecrawl/fireplexity": ("ai-agent", "开源版 Perplexity，带实时引用与流式回答，数据由 Firecrawl 供给"),
    "wassupjay/n8n-free-templates": ("ai-agent", "200+ 开箱即用的 n8n 工作流模板，含向量库、Embedding、LLM 组合"),
    "FlowiseAI/Flowise": ("ai-agent", "拖拽式搭建 AI Agent 与对话机器人，可视化编排 LLM 流程"),
    "lobehub/lobehub": ("ai-agent", "AI 团队的「调度台」：管理、定时、汇报你的多个 Agent"),
    "MoonshotAI/kimi-cli": ("ai-agent", "月之暗面官方 Kimi 命令行客户端（已归档，请改用 kimi-code）"),
    "Ido-Levi/Hephaestus": ("ai-agent", "半结构化 Agent 框架，工作流随Agent 发现的任务自动生长，而非预先编排"),
    "google-gemini/computer-use-preview": ("ai-agent", "Google 官方 Computer Use 预览版，让模型像人一样操作电脑界面"),
    "openclaw/openclaw": ("ai-agent", "主打「真干活」的个人 AI 助手，跨系统跨平台的自托管 Agent"),
    "snarktank/ralph": ("ai-agent", "自治循环 Agent：反复读取 PRD 清单，直到所有条目被逐项完成"),
    "ZekerTop/ai-cli-complete-notify": ("ai-agent", "Claude Code / Codex / Gemini CLI 任务完成提醒，支持飞书、钉钉、Telegram 等多通道推送"),
    "hellangleZ/Raffaello": ("ai-agent", "PRD 并行执行引擎，Ralph 的「更冷静更快」的孪生兄弟"),
    "HKUDS/ClawWork": ("ai-agent", "把 OpenClaw 当 AI 同事用的实战项目（作者称 11 小时赚到 15K 美元）"),
    "puzhen-ryan/xhs-toolkit": ("ai-agent", "面向 Agent 的小红书发帖与运营工具，同时提供配套 Skills"),
    "openclaw/clawhub": ("ai-agent", "OpenClaw 生态的 Skill 与插件注册中心"),
    "Lawliet-ai/openclaw-skills-Lawliet": ("ai-agent", "高质量 OpenClaw Skills 合集，专门收集「高主动性」工作流"),
    "msitarzewski/agency-agents": ("ai-agent", "一整套「AI 数字 Agency」角色库：前端专家、社区运营、创意注入、现实检验等"),
    "fathah/hermes-desktop": ("ai-agent", "Hermes Agent 的桌面伴侣客户端"),
    "yan-labs/serenity-aleabitoreddit": ("ai-agent", "可安装的推文归档 + AI 语义供应链 Skill，一条命令 npx 装到本地"),
    "nextlevelbuilder/ui-ux-pro-max-skill": ("ai-agent", "给 Agent 用的 UI/UX 设计智能 Skill，跨平台产出专业级界面"),
    "esengine/DeepSeek-Reasonix": ("ai-agent", "Go 写的可靠编码 Agent，面向复杂软件工程任务"),
    "farion1231/cc-switch": ("ai-agent", "跨平台桌面端 AI 助手，一键切换 Claude Code、Codex、OpenCode、OpenClaw 等"),
    "drona23/claude-token-efficient": ("ai-agent", "单个 CLAUDE.md 配置，让 Claude 输出更简洁，显著降低 token 消耗"),
    "linuxhsj/openclaw-zero-token": ("ai-agent", "让 OpenClaw 复用主流模型而无需自备 API Token 的方案"),
    "6551Team/opennews-mcp": ("ai-agent", "新闻聚合 + AI 评分 + 交易信号 + 实时更新的 MCP 服务"),
    "mcncarl/yichen-skills": ("ai-agent", "个人整理的 Skills 合集（仓库暂无官方简介）"),
    "chengyi-ai/native-subtitle-quote-image": ("ai-agent", "保留视频内嵌字幕、精确取帧并生成 3:4 社交长图的 Agent Skill"),
    "xiamuceer-j/MuMuAINovel": ("ai-agent", "AI 智能小说创作助手，帮你把故事点子写成完整稿件"),
    "Zie619/n8n-workflows": ("ai-agent", "n8n 全网工作流收集合集，含从官网与社区搜集的可导入 JSON"),
    "bytedance/deer-flow": ("ai-agent", "字节开源长周期 SuperAgent 框架：研究、编码、创作，沙箱 + 记忆 + 工具 + 子 Agent"),
    "666ghj/MiroFish": ("ai-agent", "简洁通用的群体智能引擎，用多 Agent 模拟推演做任何预测，含金融预测应用"),

    # ---------- 大模型训练、推理与基础设施 ----------
    "yahoo/open_nsfw": ("ai-infra", "基于 Caffe 深度神经网络的 NSFW 图像分类模型，Yahoo 开源"),
    "PaddlePaddle/PaddleGAN": ("ai-infra", "百度飞桨 GAN 库，含老照片修复、Wav2Lip 换口型、超分、人脸编辑等大量应用"),
    "XianrenYty/OldVideoRepair_PaddleGAN": ("ai-infra", "用插帧 DAIN + 上色 DeOldify + 超分 EDVR 三个模型修复老视频的实践 Notebook"),
    "Xtra-Computing/ThunderGP": ("ai-infra", "面向 FPGA 的 HLS 图计算框架，做超大规模图算法硬件加速"),
    "datawhalechina/self-llm": ("ai-infra", "《开源大模型食用指南》：Linux 下微调与部署国内外 LLM / 多模态模型"),
    "knownsec/aipyapp": ("ai-infra", "Python 与 AI 双向互操作的应用合集，涵盖「AI 用 Python」与「Python 驱动 AI」"),
    "QuantumNous/new-api": ("ai-infra", "统一大模型网关：把各家 LLM 转成 OpenAI / Claude / Gemini 兼容接口"),
    "songquanpeng/one-api": ("ai-infra", "老牌 LLM API 管理分发系统，支持十几家国内主流模型统一适配"),
    "deepseek-ai/deepseek-harness": ("ai-infra", "DeepSeek 官方 Agent Harness，核心设计是「一切皆插件」"),
    "jingyaogong/minimind": ("ai-infra", "2 小时从零训练一个 6400 万参数 LLM 的极简教学项目"),

    # ---------- 金融量化与投资研究 ----------
    "jrothschild33/learn_backtrader": ("finance", "Backtrader 中文教程笔记，系统讲清策略构建、数据结构、回测与可视化"),
    "mementum/backtrader": ("finance", "Python 回测库的事实标准，交易策略的历史表现验证用它"),
    "ZhuLinsen/daily_stock_analysis": ("finance", "LLM 驱动的多市场股票分析：多源行情 + 实时新闻 + 决策看板 + 自动推送"),
    "waditu/tushare": ("finance", "A股历史行情与财务数据爬取工具，国内量化数据基建常用"),
    "waditu/czsc": ("finance", "缠中说禅（缠论）技术分析工具，Rust 编写，覆盖股票与期货"),
    "wensongz/stock-portfolio-manager": ("finance", "个人自用的股票投资组合管理器，Rust 编写"),
    "24mlight/A_Share_investment_Agent": ("finance", "A 股投资 Agent 项目（仓库暂无官方简介）"),
    "virattt/ai-hedge-fund": ("finance", "多 Agent 模拟一支 AI 对冲基金：基本面、技术面、风险、看多看空各自成角色"),
    "wbh604/UZI-Skill": ("finance", "游资「UZI」Skills：22 维数据 × 180 条量化规则 × 17 种机构分析法，A/H/美股通吃"),
    "xbtlin/ai-berkshire": ("finance", "AI 时代的伯克希尔：巴菲特、芒格、段永平、李录四大师方法论 + 多 Agent 并行研究"),
    "Fincept-Corporation/FinceptTerminal": ("finance", "对标彭博终端的金融终端，集成行情分析、投资研究与经济数据"),
    "pythonstock/stock": ("finance", "Python 开发的股票系统，完整业务流实践项目"),
    "simonlin1212/a-stock-data": ("finance", "A 股全栈数据工具包：行情、研报、信号、资金面、财务，15 层 87 端点免 Key"),
    "Benboerba620/Benboerba620": ("finance", "零代码 × AI 投研 × 个人知识库的一体化投资研究工具包"),
    "jcdreamjc/wudao-ashare": ("finance", "悟道 A 股数据套件：26 个实时 API，专为 AI Agent 设计"),
    "sngyai/Sequoia-X": ("finance", "A 股自动选股系统，多种技术形态扫描，收盘后自动跑并推送飞书"),
    "ccxt/ccxt": ("finance", "统一加密货币交易 API，100+ 交易所与预测市场，多语言支持"),
    "ranaroussi/yfinance": ("finance", "从雅虎财经抓取行情数据的事实标准库"),
    "Micro-sheep/efinance": ("finance", "快速获取基金、股票、债券、期货数据的 Python 库，附回测与量化工具"),

    # ---------- 电子书与阅读器 ----------
    "Anxcye/anx-reader": ("reading", "AI 能力突出的电子书阅读器，支持多种格式，主打更聪明的沉浸阅读"),
    "readest/readest": ("reading", "跨平台现代电子书阅读器，接Calibre 库，支持插件与书库同步"),
    "koodo-reader/koodo-reader": ("reading", "现代电子书管理与阅读器，支持 Win/Mac/Linux/Android/iOS/Web 多端同步备份"),
    "Kareadita/Kavita": ("reading", "高性能跨平台阅读服务器，一站式管理小说与漫画书库（含 CBZ）"),
    "xincmm/sageread": ("reading", "AI 辅助阅读器，三栏布局让笔记、阅读、AI 对话同屏，适合深度阅读"),
    "MeowSalty/LocalizeEpub_For_Windows": ("reading", "C# 重写的 EPUB 本地化客户端，借繁化姬等第三方服务做繁简转换与翻译"),
    "Dujltqzv/Some-Many-Books": ("reading", "个人收藏书单仓库（作者以大量空白字符排版，纯清单项目）"),
    "baturyilmaz/wordpecker-app": ("reading", "把 Duolingo 式课程与自己的生词表结合，支持从书籍里直接摘词加入"),
    "santinic/audiblez": ("reading", "用本地 TTS（Kokoro）把 EPUB 电子书一键生成有声书"),
    "oomol-lab/pdf-craft": ("reading", "PDF 转其他格式的工具包，专注扫描书籍的结构化处理"),

    # ---------- RSS、资讯与舆情监控 ----------
    "RSSNext/Folo": ("rss-news", "AI 驱动的 RSS 阅读器，界面干净，支持 RSSHub 生态"),
    "DIYgod/RSSHub": ("rss-news", "万物皆可 RSS，把微博、B站、豆瓣、Instagram 等全网内容变成订阅源"),
    "cooderl/wewe-rss": ("rss-news", "更优雅的公众号订阅方案：私有化部署，基于微信读书生成公众号 RSS"),
    "sansan0/TrendRadar": ("rss-news", "AI 舆情与热点监控，多平台聚合 + RSS 订阅 + 关键词智能推送"),
    "newsnext/newsnow": ("rss-news", "极简风格的实时热点聚合阅读器，一屏看完今日要闻"),
    "zarazhangrui/follow-builders": ("rss-news", "AI 创作者速报：监控 X 与 YouTube 播客上的顶级 AI builder 并二次创作摘要"),

    # ---------- 爬虫与浏览器自动化 ----------
    "browserbase/stagehand": ("crawl-browser", "浏览器数据提取与交互 SDK，官方推荐与 Claude Code、Codex 搭配使用"),
    "apify/crawlee": ("crawl-browser", "Apify 出品的 Node.js 爬虫与浏览器自动化库，专为 AI/LLM 数据管道设计"),
    "unclecode/crawl4ai": ("crawl-browser", "开源爬虫，把任意网站转成干净的 LLM 友好 Markdown"),
    "h4ckf0r0day/obscura": ("crawl-browser", "面向 AI Agent 的无头浏览器，带反检测能力，兼顾网页抓取"),

    # ---------- 实用工具与效率软件 ----------
    "xinyueyongliang/FileRcovery": ("tools", "实现了三种文件系统的数据恢复工具，偏底层实践"),
    "easychen/LazyBoardExt": ("tools", "Chrome 扩展机器人：定时采集数据并推送到指定接口"),
    "wanglin2/mind-map": ("tools", "SimpleMindMap 思维导图，交互简洁、功能扎实的开源导图工具"),
    "xiaobaigroup/ClashBox": ("tools", "HarmonyOS NEXT 上的代理客户端，ArkTS + ArkUI 实现"),
    "chen08209/FlClash": ("tools", "基于 ClashMeta 的多平台代理客户端，Flutter 编写，简洁无广告"),
    "ImranR98/Obtainium": ("tools", "直接从项目源站拉取 APK 更新，绕开应用商店版本滞后"),
    "zhongyang219/TrafficMonitor": ("tools", "Windows 桌面悬浮窗，显示网速、CPU、内存，支持任务栏显示与换肤"),
    "Xinrea/JPet": ("tools", "C++ + WebView2 的 Live2D 桌面宠物"),
    "eythaann/Seelen-UI": ("tools", "高度可定制的 Windows 10/11 桌面环境：启动器、Dock、Finder 一体化"),
    "Devolutions/UniGetUI": ("tools", "包管理器的图形前端，统一管理 winget、choco、scoop 等各家包管理器"),
    "Cp0204/quark-auto-save": ("tools", "夸克网盘自动化：签到、自动转存、命名整理、推送提醒、刷新媒体库"),
    "Usagi-org/ai-goofish-monitor": ("tools", "基于 Playwright + AI 的闲鱼多任务实时监控与筛选系统，带后台管理 UI"),
    "blinkospace/blinko": ("tools", "开源自托管的个人 AI 笔记，强调隐私，数据留在本地"),
    "microsoft/markitdown": ("tools", "微软官方工具：把各类文件与 Office 文档统一转成 Markdown"),
    "x1ao4/douban-api": ("tools", "基于豆瓣移动端 API 的影视榜单接口服务"),
    "AnInsomniacy/rayburst": ("tools", "重新定义开源下载体验的下载管理器"),
    "reactive-resume/reactive-resume": ("tools", "隐私优先的开源简历生成器，可定制、可移植、免费"),
    "galaxy-s10/billd-desk": ("tools", "基于 Vue3 + WebRTC 的远程桌面与游戏串流，自建可控"),
    "sumimakito/Mac-Duo": ("tools", "在 MacBook 上复刻 iPhone「灵动岛」Duo 效果的小工具"),
    "tobi/disktree": ("tools", "用树图空间找方式清理磁盘占用，Rust + GPUI 实现"),
    "iawia002/lux": ("tools", "Go 编写的高效视频下载库与命令行工具"),

    # ---------- Android / 移动端开发 ----------
    "CarGuo/GSYVideoPlayer": ("mobile", "Android 通用视频播放器框架，集成 IJKPlayer、ExoPlayer，支持 16K 分页与弹幕"),
    "CarGuo/gsy_github_app_flutter": ("mobile", "Flutter 版 GitHub App，功能完整，适合作为 Flutter 学习工程"),
    "the1812/Bilibili-Evolved": ("mobile", "功能强大的哔哩哔哩油猴增强脚本（按移动端增强归类）"),
    "Soulghost/InfiniteSpringBoard": ("mobile", "锤子科技「无限屏」的 iOS 实现复刻"),
    "barry-ran/QtScrcpy": ("mobile", "基于 Qt 的 Android 实时投屏与控制软件，跨平台"),
    "gkd-kit/gkd": ("mobile", "基于无障碍能力的 Android 自动点击应用，支持高级选择器与订阅规则"),
    "ChaoMixian/vFlow": ("mobile", "Android 图形化自动化工具，把动作模块拼成工作流完成重复点击操作"),
    "DrKLO/Telegram": ("mobile", "Telegram 安卓客户端官方源码"),
    "elyesmansour/compose-floating-tab-bar": ("mobile", "Jetpack Compose 悬浮标签栏，仿 iOS 26 Liquid Glass 效果"),
    "CashewTeam/BigBang_NovaText": ("mobile", "老罗 Smartisan BigBang 输入法的社区重制版"),
    "RANH-F/Smartisan-original-launcher": ("mobile", "让原版 Smartisan Launcher 在当代安卓上重新跑起来，还原简洁克制的美学"),
    "SangLuoCN/OneStep4": ("mobile", "小项目，仓库信息仅标注 Designed By SangLuo"),

    # ---------- 影音媒体与家庭娱乐 ----------
    "CTalvio/Ultrachromic": ("media", "Jellyfin 主题插件：色相动态取色，明暗主题随封面变化"),
    "ChineseSubFinder/ChineseSubFinder": ("media", "自动中文字幕下载，支持 Emby / Jellyfin / Plex / Sonarr / Radarr 等媒体库"),
    "awesome-jellyfin/awesome-jellyfin": ("media", "Jellyfin 插件、主题与教程的精选合集"),
    "DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult": ("media", "Jellyfin/Emby 元数据插件，抓取多个成人站点的信息"),
    "jellyfin/jellyfin-plugin-template": ("media", "Jellyfin 插件开发官方模板"),
    "metatube-community/jellyfin-plugin-metatube": ("media", "MetaTube 的 Jellyfin/Emby 插件，含自动翻译与人脸识别"),
    "lizongying/my-tv": ("media", "开源电视直播软件，安装即用"),
    "Eanya-Tonic/CCTV_Viewer": ("media", "简易电视浏览器，方便在机顶盒上收看网页视频"),
    "Richasy/Bili.Copilot": ("media", "B 站第三方 Windows 桌面客户端，WinUI 3 + Windows App SDK 原生实现"),
    "LibreSpark/LibreTV": ("media", "一分钟搭建的影视站，支持 Docker 部署"),
    "youhunwl/TVAPP": ("media", "全网安卓电视盒子应用与影视仓接口配置源合集，分类整理并支持自动更新"),
    "bggRGjQaUbCoE/PiliPlus": ("media", "Flutter 写的第三方 B 站客户端，支持 iOS / 桌面多端"),

    # ---------- 硬件、系统与嵌入式 ----------
    "LiteOS/LiteOS": ("system", "华为 LiteOS 轻量级物联网操作系统源码与开发手册"),
    "FuchsiaOS/Fuchsia-OS-tutorial": ("system", "Fuchsia OS 学习资料与教程汇总"),
    "FuchsiaOS/FuchsiaOS-docs-zh_CN": ("system", "Fuchsia OS 官方文档简体中文版"),
    "FASTSHIFT/X-TRACK": ("system", "支持离线地图与轨迹记录的 GPS 自行车码表，C + LVGL"),
    "LeiWang1999/FPGA": ("system", "FPGA 入门与优质项目文章合集，含 Vivado / Xilinx 相关资料"),
    "Forairaaaaa/Monica": ("system", "DIY AMOLED 屏智能手表，硬件加固件全自制"),
    "thunder439/QNASMINI": ("system", "6 盘位 2.5 寸 NAS 硬件项目"),
    "CentyLab/PocketPD": ("system", "PocketPD 开源固件项目"),
    "mx3353672833-debug/moto-gps-waveshare": ("system", "装在车把上的圆屏导航终端：ESP32-S3 1.75C AMOLED + iPhone App，手机算路线、圆屏显示路口与速度"),
    "Sunbelife/Snowboard-IconPack-for-Smartisan-OS": ("system", "Smartisan OS 的雪地主题图标包"),
    "Sunbelife/get_smartisan_icon_pack": ("system", "从 Smartisan OS 提取 1400+ 图标的脚本"),
    "SmartisanTech/android": ("system", "Smartisan OS 完整源码与构建清单"),
    "CashewTeam/awesome-smartisanOS": ("system", "SmartisanOS 相关优质项目、工具、资源与文章汇总"),
    "Robotips/uConfig": ("system", "从 PDF 数据手册提取引脚定义并生成 KiCad 符号与库文件"),
    "joanbono/awesome-kicad": ("system", "KiCad 插件与资源精选合集"),
    "dsa-t/jlc-kicad-lib-loader": ("system", "在 KiCad 里批量浏览下载立创商城 / LCSC 元件库"),
    "medisoft/pcb-coil-generator": ("system", "EasyEDA Pro 的 PCB 线圈生成器"),
    "KingKongRobotics/jumper": ("system", "开源螃蟹机器人硬件项目"),

    # ---------- 前端与网页开发 ----------
    "kkuchta/css-only-chat": ("frontend", "前端零 JavaScript 的异步聊天界面，纯 CSS 实现的怪物级实验"),
    "joshajohnson/Hub16": ("frontend", "自制 16 键宏键盘，带两个旋钮编码器与四口 USB Hub，主打灯光效果"),

    # ---------- 学习资料与教程 ----------
    "jackfrued/Python-100-Days": ("learning", "Python 从新手到大师的 100 天学习路线，含 Jupyter Notebook"),
    "jaywcjlove/linux-command": ("learning", "Linux 命令大全搜索工具：手册、详解、学习资料全收录"),
    "nndl/nndl": ("learning", "邱锡鹏《神经网络与深度学习》第二版电子书与配套学习资源"),
    "CyC2018/CS-Notes": ("learning", "技术面试必备：算法、操作系统、计算机网络、系统设计笔记"),
    "AobingJava/JavaFamily": ("learning", "Java 面试与学习指南，覆盖 Java 程序员需掌握的核心知识"),
    "HelloWorld521/Java": ("learning", "Java 项目实战练习集"),
    "DuGuQiuBai/Java": ("learning", "「27 天成为 Java 大神」系列教程"),
    "Snailclimb/JavaGuide": ("learning", "Java 面试与后端通用面试指南，已扩展到 AI 应用开发"),
    "SwiftGGTeam/the-swift-programming-language-in-chinese": ("learning", "Apple 官方《Swift 编程语言》中文版"),
    "xiaobaiTech/golangFamily": ("learning", "超全 Golang 面试题、学习指南与知识图谱"),
    "justjavac/free-programming-books-zh_CN": ("learning", "免费的中文计算机编程书籍汇总"),
    "ruanyf/free-books": ("learning", "互联网上的免费书籍索引"),
    "sindresorhus/awesome": ("learning", "覆盖各行各业的 Awesome Lists 总目录"),
    "xiaolai/bitcoin-whitepaper-chinese-translation": ("learning", "比特币白皮书中文全译（仓库暂无官方简介）"),
    "fireinthehole2019/awesome-reverse-engineering": ("learning", "全平台逆向工程资源：3500+ 开源工具与2300 篇文章"),
    "beihaili/Get-Started-with-Web3": ("learning", "双语 AI-native Web3 课程：钱包、比特币、以太坊、DeFi、DAO、llms.txt 与 MCP"),
    "ProbiusOfficial/Hello-CTF": ("learning", "面向零基础新手的 CTF 入门开源教程，同时补信息差"),
    "luongnv89/claude-howto": ("learning", "图解式 Claude Code 指南，从基础概念到高级 Agent，附可直接复制的模板"),
    "ZuodaoTech/everyone-can-use-english": ("learning", "《人人都能用英语》开源教材与配套资源"),
    "hesamsheikh/awesome-openclaw-usecases": ("learning", "OpenClaw 社区用例合集，看别人怎么用 Agent 省事"),
    "leereilly/games": ("learning", "GitHub 上架游戏的归档清单，覆盖各平台与引擎"),
"bobeff/open-source-games": ("learning", "开源游戏清单索引"),

    # ---------- 游戏与模拟器 ----------
    "shadps4-emu/shadPS4": ("games", "C++ 编写的 PlayStation 4 模拟器，支持 Win/Linux/macOS/FreeBSD"),
    "KsanaDock/Microverse": ("games", "基于 Godot 4 的 AI 社会沙盒：虚拟世界里的角色各有性格与关系，模拟群体智能"),

    # ---------- 隐私、安全与逆向 ----------
    "minbrowser/min": ("security", "快速、极简、注重隐私的浏览器"),
    "LadybirdBrowser/ladybird": ("security", "真正独立的浏览器，从零自研引擎，不依赖 Chromium"),
    "DimensionDev/Flare": ("security", "一个客户端聚合浏览 Mastodon、Bluesky、X、Misskey、Nostr、Pixiv、RSS"),
    "assafdori/bypass-mdm": ("security", "绕过 macOS 的 MDM 设备管理限制（至 Golden Gate 版本）"),

    # ---------- 生活、健康与个人成长 ----------
    "evil-huawei/evil-huawei": ("life", "记录华为历次争议事件的档案库"),
    "Snouzy/workout-cool": ("life", "开源健身教练平台：制定训练计划、追踪进度、内置动作数据库"),
    "easychen/lean-side-bussiness": ("life", "《精益副业》：程序员如何优雅地做副业"),
    "easychen/opc-methodology": ("life", "《一人企业方法论》第二版，非技术人群做副业的通用框架"),
    "Gar-b-age/CookLikeHOC": ("life", "像老乡鸡那样做饭：按《老乡鸡菜品溯源报告》整理的菜谱"),
    "eternity4719/HowToLiveBetter": ("life", "高性价比人生指南：长寿防病、急救、理财、法律红线，每条标注成本与证据等级"),
}

#修正几个名字写错的键（保持与GitHub 一致）
ALIAS = {
    "sageread": "xincmm/sageread",
    "blinko/blinko": "blinkospace/blinko",
}